# Generated by Django 4.2.7 on 2023-12-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
