# Generated by Django 4.2.7 on 2023-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachernotification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
